ci (#8)

diff --git a/.github/workflows/docker-build-deploy.yml b/.github/workflows/docker-build-deploy.yml
--- a/.github/workflows/docker-build-deploy.yml
+++ b/.github/workflows/docker-build-deploy.yml
@@ -4,7 +4,7 @@ on:
   pull_request:
     types: [closed]  # This triggers the workflow when a PR is closed
     branches:
-      - main
+      - EN_2.2.0_AWS_N1_ANG_FE
 
 permissions:
   contents: read  # Allow reading contents to access labels
@@ -12,7 +12,7 @@ permissions:
 
 env: # Centralized commonplace for reusable values
   DOCKERHUB_LOGIN_URL: "https://hub.docker.com/v2/users/login"
-  DOCKERHUB_REPOSITORY: "bibianamagdelene/test"
+  DOCKERHUB_REPOSITORY: "innoart/genesis"
   DOCKER_IMAGE_PREFIX: "EN_2.2.0_AWS_N1_ANG_FE_001"
   DOCKERHUB_TAGS_URL_BASE: "https://hub.docker.com/v2/repositories"
   GITHUB_API_BASE_URL: "https://api.github.com/repos"
@@ -38,10 +38,6 @@ jobs:
       - name: Debug deploy_target
         run: echo "Deploy target is ${{ steps.set_env.outputs.deploy_target }}"
       
-
-      - name: Check out code
-        uses: actions/checkout@v3
-
       - name: Build Docker image
         id: set_image_name
         run: |
@@ -69,8 +65,6 @@ jobs:
       AWS_INSTANCE_ID: 'i-05a83859adbf2a8ac'
       AWS_REGION: 'ap-south-1'
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
 
       - name: DockerHub Login to get token
         id: dockerhub_login
@@ -183,5 +177,15 @@ jobs:
             --instance-id ${{ env.AWS_INSTANCE_ID }} \
             --region ${{ env.AWS_REGION }}
                   
+  capture_invalid_deploy_target:
+    runs-on: ubuntu-latest
+    needs: build
+    if: needs.build.outputs.deploy_target != 'AWS' && needs.build.outputs.deploy_target != 'all'
+    steps:
+      - name: Capture Invalid Deploy Target
+        run: |
+          echo "ERROR: Invalid deploy_target value: '${{ needs.build.outputs.deploy_target }}'"
+          echo "::error title=Invalid Deploy Target::Expected 'AWS' or 'all', but got '${{ needs.build.outputs.deploy_target }}'"
+          exit 1
     
     
